"""Linked-tag reasoning pass: franchise tags IGDB did not give.

IGDB's franchise field is sparse (about a third of matched games carry one), so
this pass proposes a franchise for games whose title plainly belongs to one.
Rules are (title pattern -> franchise); they only fire for games that have no
franchise tag yet, and every hit lands as state=proposed for review in the UI
(dashed chip, tick to accept, cross to reject). Names follow IGDB's franchise
names where one exists, so accepted proposals merge with IGDB's own tags.
"""
import re

from . import db, tags

SOURCE = "reasoning"

RULES = [
    # Nintendo
    (r"^(new )?super mario|^mario (kart|party|golf|tennis|sports|bros|& (luigi|sonic))|^paper mario|^dr\.? mario|"
     r"^captain toad|^luigi's mansion|^super mario maker|^mario & luigi", "Mario"),
    (r"^yoshi|poochy & yoshi", "Yoshi"),
    (r"^wario|^warioware", "Wario"),
    (r"donkey kong", "Donkey Kong"),
    (r"legend of zelda|^hyrule warriors", "The Legend of Zelda"),
    (r"^pokemon|^pocket monsters|^(meitantei|detective) pikachu|^super pokemon rumble", "Pokémon"),
    (r"^kirby", "Kirby"),
    (r"^metroid", "Metroid"),
    (r"^fire emblem", "Fire Emblem"),
    (r"^star fox|^lylat wars|^starwing|^super star fox", "Star Fox"),
    (r"^pilotwings", "Pilotwings"),
    (r"^super smash bros", "Super Smash Bros."),
    (r"^animal crossing", "Animal Crossing"),
    (r"^punch-out", "Punch-Out!!"),
    (r"^ice climber", "Ice Climber"),
    (r"^kid icarus", "Kid Icarus"),
    (r"^xenoblade", "Xenoblade"),
    (r"^tomodachi", "Tomodachi"),
    (r"^(more )?brain training|^dr\.? kawashima|brain age", "Brain Age"),
    (r"^nintendogs", "Nintendogs"),
    (r"^picross", "Picross"),
    (r"^rhythm (heaven|paradise|tengoku)", "Rhythm Heaven"),
    (r"new style boutique|^style savvy", "Style Savvy"),
    (r"art academy", "Art Academy"),
    (r"^chibi-robo", "Chibi-Robo!"),
    (r"^advance wars|^famicom wars", "Wars"),
    (r"^golden sun", "Golden Sun"),
    (r"^f-zero", "F-Zero"),
    (r"^bayonetta", "Bayonetta"),
    (r"^sin & punishment", "Sin and Punishment"),
    (r"^ultimate nes remix|^nes remix", "NES Remix"),
    # Sega
    (r"^sonic|^mario & sonic|^sonic boom", "Sonic the Hedgehog"),
    (r"^super monkey ball", "Super Monkey Ball"),
    (r"^golden axe", "Golden Axe"),
    (r"^shinobi|^shadow dancer", "Shinobi"),
    (r"^after burner", "After Burner"),
    (r"^space harrier", "Space Harrier"),
    (r"^outrun", "OutRun"),
    (r"^crazy taxi", "Crazy Taxi"),
    (r"^alex kidd", "Alex Kidd"),
    (r"^phantasy star", "Phantasy Star"),
    (r"^virtua fighter", "Virtua Fighter"),
    (r"^streets of rage", "Streets of Rage"),
    (r"^wonder boy", "Wonder Boy"),
    (r"^fantasy zone", "Fantasy Zone"),
    # Capcom
    (r"^mega ?man|^rockman", "Mega Man"),
    (r"street fighter", "Street Fighter"),
    (r"^resident evil|^biohazard", "Resident Evil"),
    (r"^monster hunter", "Monster Hunter"),
    (r"^devil may cry", "Devil May Cry"),
    (r"^final fight", "Final Fight"),
    (r"^ghosts ?'?n ?goblins|^ghouls ?'?n ?ghosts|^gargoyle's quest|^demon's crest", "Ghosts 'n Goblins"),
    (r"^marvel vs\.? capcom|^x-men vs|^marvel super heroes vs", "Marvel vs. Capcom"),
    (r"^ace attorney|phoenix wright", "Ace Attorney"),
    (r"^breath of fire", "Breath of Fire"),
    (r"^1942|^1943|^1941|^1944|^19xx", "194X"),
    (r"^bionic commando", "Bionic Commando"),
    (r"^strider", "Strider"),
    (r"^captain commando", "Captain Commando"),
    (r"^alien vs\.? predator|^aliens vs\.? predator", "Alien vs. Predator"),
    # Konami
    (r"^castlevania|^akumajou", "Castlevania"),
    (r"^contra|^super c$|^probotector", "Contra"),
    (r"^metal gear", "Metal Gear"),
    (r"^gradius|^salamander|^life force|^nemesis", "Gradius"),
    (r"^silent hill", "Silent Hill"),
    (r"^teenage mutant ninja turtles|^tmnt|nickelodeon teenage mutant", "Teenage Mutant Ninja Turtles"),
    (r"^track & field|^international track & field|^hyper sports", "Track & Field"),
    (r"^pro evolution soccer|^winning eleven|^pes ", "Pro Evolution Soccer"),
    (r"^yu-gi-oh", "Yu-Gi-Oh!"),
    (r"^suikoden", "Suikoden"),
    (r"^twinbee|^pop'n twinbee", "TwinBee"),
    (r"^goemon|^mystical ninja", "Ganbare Goemon"),
    (r"^sunset riders", "Sunset Riders"),
    (r"^rush'?n attack|^green beret", "Rush'n Attack"),
    (r"^blades of steel", "Blades of Steel"),
    (r"^frogger", "Frogger"),
    (r"^dance dance revolution", "Dance Dance Revolution"),
    # Square Enix / Atlus
    (r"final fantasy|^theatrhythm|^chocobo", "Final Fantasy"),
    (r"^dragon quest|^dragon warrior", "Dragon Quest"),
    (r"^kingdom hearts", "Kingdom Hearts"),
    (r"^chrono (trigger|cross)", "Chrono"),
    (r"^secret of mana|^trials of mana|^seiken densetsu|^legend of mana|^sword of mana", "Mana"),
    (r"^bravely", "Bravely"),
    (r"^parasite eve|^the 3rd birthday", "Parasite Eve"),
    (r"^shin megami tensei|^persona|^devil survivor|^soul hackers|^strange journey|^megami tensei|persona q",
     "Shin Megami Tensei"),
    (r"^etrian", "Etrian Odyssey"),
    (r"^radiant historia", "Radiant Historia"),
    (r"^star ocean", "Star Ocean"),
    (r"^saga |^romancing saga|^saga frontier|^the alliance alive|^the legend of legacy", "SaGa"),
    (r"^actraiser", "ActRaiser"),
    (r"^ogre battle|^tactics ogre", "Ogre Battle"),
    (r"^front mission", "Front Mission"),
    (r"^valkyrie profile", "Valkyrie Profile"),
    (r"^xenogears|^xenosaga", "Xeno"),
    (r"^tales of", "Tales"),
    (r"^ys ", "Ys"),
    (r"^lufia", "Lufia"),
    # Sony first party
    (r"^gran turismo", "Gran Turismo"),
    (r"^god of war", "God of War"),
    (r"^ratchet & clank|^ratchet and clank", "Ratchet & Clank"),
    (r"^jak (ii|3|x|and daxter)|^daxter", "Jak and Daxter"),
    (r"^sly (cooper|2|3)", "Sly Cooper"),
    (r"^ape escape|^ape academy", "Ape Escape"),
    (r"^twisted metal", "Twisted Metal"),
    (r"^wipeout( 64| xl| 2097| fusion| pure| pulse| hd)?$", "Wipeout"),
    (r"^crash bandicoot|^crash team racing|^ctr:", "Crash Bandicoot"),
    (r"^spyro", "Spyro the Dragon"),
    (r"^syphon filter", "Syphon Filter"),
    (r"^ico$|^shadow of the colossus", "Ico"),
    (r"^dark cloud", "Dark Cloud"),
    (r"^killzone", "Killzone"),
    (r"^patapon", "Patapon"),
    (r"^locoroco", "LocoRoco"),
    (r"^hot shots golf|^everybody's golf", "Everybody's Golf"),
    # Others: Namco, Taito, SNK, Sega, Irem, Tecmo, Data East, Atari, Midway
    (r"^tekken", "Tekken"),
    (r"^ridge racer|^r4:", "Ridge Racer"),
    (r"^ace combat", "Ace Combat"),
    (r"^katamari|^we love katamari", "Katamari"),
    (r"^pac-?man|^pac-mania|^ms\.? pac-man|^pacman", "Pac-Man"),
    (r"^galaga|^galaxian|^galaga ", "Galaga"),
    (r"^dig dug", "Dig Dug"),
    (r"^xevious", "Xevious"),
    (r"^mappy", "Mappy"),
    (r"^dragon spirit|^dragon saber", "Dragon Spirit"),
    (r"^dragon buster", "Dragon Buster"),
    (r"^sky kid", "Sky Kid"),
    (r"^rolling thunder", "Rolling Thunder"),
    (r"^splatterhouse", "Splatterhouse"),
    (r"tower of druaga|^druaga", "The Tower of Druaga"),
    (r"^klonoa", "Klonoa"),
    (r"^soul calibur|^soulcalibur|^soul edge", "Soulcalibur"),
    (r"^time crisis|^point blank", "Time Crisis"),
    (r"^bubble bobble|^puzzle bobble|^bust-a-move|^rainbow islands|^parasol stars", "Bubble Bobble"),
    (r"^space invaders", "Space Invaders"),
    (r"^arkanoid", "Arkanoid"),
    (r"^darius", "Darius"),
    (r"^elevator action", "Elevator Action"),
    (r"^chase h\.?q|^super chase", "Chase H.Q."),
    (r"^operation wolf|^operation thunderbolt", "Operation Wolf"),
    (r"^the newzealand story|^kiwi kraze", "The NewZealand Story"),
    (r"^metal slug", "Metal Slug"),
    (r"king of fighters", "The King of Fighters"),
    (r"^samurai shodown|^samurai spirits", "Samurai Shodown"),
    (r"^fatal fury|^garou", "Fatal Fury"),
    (r"^art of fighting", "Art of Fighting"),
    (r"^ikari", "Ikari Warriors"),
    (r"^athena|^psycho soldier", "Athena"),
    (r"^r-type", "R-Type"),
    (r"^ninja (spirit|gaiden)|^shadow warriors", "Ninja Gaiden"),
    (r"^hammerin' harry", "Hammerin' Harry"),
    (r"^tecmo (super )?bowl", "Tecmo Bowl"),
    (r"^rygar", "Rygar"),
    (r"^dead or alive", "Dead or Alive"),
    (r"^bad dudes", "Bad Dudes"),
    (r"^joe & mac|^caveman ninja", "Joe & Mac"),
    (r"^burgertime", "BurgerTime"),
    (r"^karnov", "Karnov"),
    (r"^double dragon", "Double Dragon"),
    (r"^river city|^kunio|^nekketsu|^renegade$|^super dodge ball", "Kunio-kun"),
    (r"^centipede|^millipede", "Centipede"),
    (r"^asteroids", "Asteroids"),
    (r"^missile command", "Missile Command"),
    (r"^marble madness", "Marble Madness"),
    (r"^gauntlet", "Gauntlet"),
    (r"^paperboy", "Paperboy"),
    (r"^rampart", "Rampart"),
    (r"^mortal kombat|^ultimate mortal kombat", "Mortal Kombat"),
    (r"^nba jam", "NBA Jam"),
    (r"^smash t\.?v|^super smash t\.?v|^total carnage", "Smash TV"),
    (r"^rampage", "Rampage"),
    (r"^spy hunter|^super spy hunter", "Spy Hunter"),
    (r"^san francisco rush|^rush 2:", "San Francisco Rush"),
    (r"^cruis'n", "Cruis'n"),
    (r"^hydro thunder", "Hydro Thunder"),
    (r"^ready 2 rumble", "Ready 2 Rumble Boxing"),
    (r"^joust$", "Joust"),
    (r"^defender( ii)?$", "Defender"),
    (r"^robotron", "Robotron"),
    (r"^q\*bert|^q-bert", "Q*bert"),
    (r"^toki", "Toki"),
    (r"^snow bros", "Snow Bros."),
    (r"^dodonpachi|^donpachi", "DonPachi"),
    (r"^raiden", "Raiden"),
    (r"^turrican", "Turrican"),
    (r"^lode runner|^championship lode runner", "Lode Runner"),
    (r"^boulder dash", "Boulder Dash"),
    (r"^pitfall", "Pitfall!"),
    (r"^wizards & warriors|^ironsword", "Wizards & Warriors"),
    (r"^battletoads", "Battletoads"),
    (r"^r\.c\. pro-am", "R.C. Pro-Am"),
    (r"^banjo", "Banjo-Kazooie"),
    (r"^conker", "Conker"),
    (r"^dizzy|^fantastic adventures of dizzy|^treasure island dizzy|^wonderland dizzy|^go! dizzy", "Dizzy"),
    (r"^micro machines", "Micro Machines"),
    (r"^bomberman|^dynablaster|^super bomberman", "Bomberman"),
    (r"^adventure island", "Adventure Island"),
    (r"^bonk|^bc kid|^pc kid", "Bonk"),
    (r"^bubsy", "Bubsy"),
    (r"^clay ?fighter", "ClayFighter"),
    (r"^earthworm jim", "Earthworm Jim"),
    (r"^aero the acro-bat", "Aero the Acro-Bat"),
    (r"^zero the kamikaze", "Aero the Acro-Bat"),
    (r"^the lost vikings|^lost vikings", "The Lost Vikings"),
    (r"^rock n'? roll racing", "Rock n' Roll Racing"),
    (r"^blackthorne", "Blackthorne"),
    (r"^ultima(:| [ivx]|$)", "Ultima"),
    (r"^wing commander", "Wing Commander"),
    (r"^populous", "Populous"),
    (r"^syndicate", "Syndicate"),
    (r"^theme park", "Theme Park"),
    (r"^sid meier's civilization|^civilization", "Civilization"),
    (r"^desert strike|^jungle strike|^urban strike|^nuclear strike|^soviet strike", "Strike"),
    (r"^road rash", "Road Rash"),
    (r"^skate or die|^ski or die", "Skate or Die"),
    (r"^snowboard kids", "Snowboard Kids"),
    (r"^extreme-g", "Extreme-G"),
    (r"^gex", "Gex"),
    (r"^star soldier|^starship hector|^hector", "Star Soldier"),
    (r"^quake", "Quake"),
    (r"^doom( ii| 64|$)", "Doom"),
    (r"^hexen|^heretic", "Heretic"),
    (r"^starcraft", "StarCraft"),
    (r"^vigilante 8", "Vigilante 8"),
    (r"^chameleon twist", "Chameleon Twist"),
    (r"^fighters destiny|^fighter destiny", "Fighters Destiny"),
    (r"^bases loaded|^super bases loaded", "Bases Loaded"),
    (r"^r\.b\.i\. baseball|^super r\.b\.i", "R.B.I. Baseball"),
    (r"^baseball stars", "Baseball Stars"),
    (r"^tetris|^super tetris|^wordtris|^hatris", "Tetris"),
    (r"^solomon's key|^fire 'n ice", "Solomon's Key"),
    (r"^kid niki", "Kid Niki"),
    (r"^ninja jajamaru", "Ninja JaJaMaru-kun"),
    (r"^hydlide", "Hydlide"),
    (r"^startropics|^zoda's revenge", "StarTropics"),
    (r"^power blade", "Power Blade"),
    (r"^blaster master|^chou-wakusei", "Blaster Master"),
    (r"^fifa", "FIFA"),
    (r"^madden", "Madden NFL"),
    (r"^nhl ", "NHL"),
    (r"^tony hawk", "Tony Hawk's"),
    (r"^ssx", "SSX"),
    (r"^need for speed", "Need for Speed"),
    (r"^burnout", "Burnout"),
    (r"^midnight club", "Midnight Club"),
    (r"^grand theft auto|^gta ", "Grand Theft Auto"),
    (r"^timesplitters", "TimeSplitters"),
    (r"^prince of persia", "Prince of Persia"),
    (r"^psychonauts", "Psychonauts"),
    (r"^armored core", "Armored Core"),
    (r"^colin mcrae|^dirt ", "Colin McRae"),
    (r"^wrc", "WRC"),
    (r"^f1 |^formula (1|one)|^f-1 ", "Formula One"),
    (r"^army of two", "Army of Two"),
    (r"^007|^james bond|^goldeneye", "James Bond"),
    (r"^tenchu", "Tenchu"),
    (r"^oddworld", "Oddworld"),
    (r"^driver", "Driver"),
    (r"^tomba", "Tomba!"),
    (r"^mega man legends", "Mega Man"),
    (r"^dragon ball", "Dragon Ball"),
    (r"^naruto", "Naruto"),
    (r"^one piece", "One Piece"),
    (r"^inazuma eleven", "Inazuma Eleven"),
    (r"^yo-kai watch", "Yo-kai Watch"),
    (r"^professor layton|^layton's", "Professor Layton"),
    (r"^project x zone", "Project X Zone"),
    (r"^senran kagura", "Senran Kagura"),
    (r"^zero escape", "Zero Escape"),
    (r"^corpse party", "Corpse Party"),
    (r"^hatsune miku|^project diva|^project mirai", "Hatsune Miku"),
    (r"^harvest moon|^story of seasons|^bokujou", "Harvest Moon"),
    (r"^rune factory", "Rune Factory"),
    (r"^cooking mama|^gardening mama", "Cooking Mama"),
    (r"^hello kitty", "Hello Kitty"),
    (r"^lego|^la (grande )?lego|^the lego movie", "LEGO"),
    (r"star wars", "Star Wars"),
    (r"harry potter", "Harry Potter"),
    (r"lord of the rings|the hobbit|^lego (der herr|el senor|le seigneur|der hobbit|el hobbit)", "The Lord of the Rings"),
    (r"^batman|^lego batman", "Batman"),
    (r"spider-man", "Spider-Man"),
    (r"^x-men|^wolverine", "X-Men"),
    (r"^transformers", "Transformers"),
    (r"^power rangers", "Power Rangers"),
    (r"^skylanders", "Skylanders"),
    (r"^disney infinity", "Disney Infinity"),
    (r"spongebob", "SpongeBob SquarePants"),
    (r"^scooby-doo", "Scooby-Doo"),
    (r"^the simpsons|^simpsons", "The Simpsons"),
    (r"^the sims|^sims ", "The Sims"),
    (r"^worms", "Worms"),
    (r"^lemmings", "Lemmings"),
    (r"^rayman|^rabbids", "Rayman"),
    (r"splinter cell", "Splinter Cell"),
    (r"ghost recon", "Ghost Recon"),
    (r"^shrek", "Shrek"),
    (r"^madagascar|^penguins of madagascar", "Madagascar"),
    (r"^ice age", "Ice Age"),
    (r"^kung fu panda", "Kung Fu Panda"),
    (r"^how to train your dragon", "How to Train Your Dragon"),
    (r"^cars 2|^disney planes|^cars:", "Cars"),
    (r"^toy story", "Toy Story"),
    (r"^finding nemo", "Finding Nemo"),
    (r"^disney frozen|^frozen:", "Frozen"),
    (r"^jewel quest", "Jewel Quest"),
    (r"^jewel master", "Jewel Master"),
    (r"^jewel link", "Jewel Link"),
    (r"^mystery case files", "Mystery Case Files"),
    (r"^imagine", "Imagine"),
    (r"^petz", "Petz"),
    (r"^monster high", "Monster High"),
    (r"^moshi monsters", "Moshi Monsters"),
    (r"^wwe|^wcw|^wwf", "WWE"),
    (r"^pinball hall of fame", "Pinball Hall of Fame"),
    (r"^puzzler", "Puzzler"),
    (r"^farming simulator", "Farming Simulator"),
    (r"^rollercoaster tycoon", "RollerCoaster Tycoon"),
    (r"^shovel knight", "Shovel Knight"),
    (r"^shantae", "Shantae"),
    (r"^cave story", "Cave Story"),
    (r"^terraria", "Terraria"),
    (r"^minecraft", "Minecraft"),
    (r"^scribblenauts", "Scribblenauts"),
    (r"^no more heroes", "No More Heroes"),
    (r"^tiger woods", "PGA Tour"),
    (r"^wipeout( 2| 3|: create)", "Wipeout (TV)"),
    (r"^the amazing spider-man", "Spider-Man"),
    (r"^thor:|^captain america|^green lantern|^iron man", "Marvel"),
    (r"^lego marvel", "Marvel"),
]
_COMPILED = [(re.compile(p, re.I), f) for p, f in RULES]


def propose(source=SOURCE, dry=False):
    """Propose franchise tags for games without one. Returns {proposed, games_without_franchise, sample}."""
    tags.ensure()
    conn = db.connect()
    have = {r["game_id"] for r in conn.execute("SELECT game_id FROM tags WHERE kind='franchise'")}
    rows = conn.execute("SELECT id, title, system FROM games ORDER BY system, title").fetchall()
    out, sample = [], []
    for g in rows:
        if g["id"] in have:
            continue
        hits = [fr for rx, fr in _COMPILED if rx.search(g["title"] or "")]
        for fr in dict.fromkeys(hits):
            out.append({"game_id": g["id"], "tag": fr, "kind": "franchise"})
            if len(sample) < 40:
                sample.append(f"{g['system']}: {g['title']} -> {fr}")
    n = 0 if dry else tags.import_proposals(out, source)
    return {"proposed": n if not dry else len(out), "games_without_franchise": len(rows) - len(have), "sample": sample}
